# Generated by Django 4.2.27 on 2026-01-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Handyman', 'Handyman')], max_length=100)),
                ('registration_code', models.CharField(max_length=100)),
                ('trade_name', models.CharField(max_length=100)),
                ('nzbn', models.CharField(max_length=100)),
            ],
        ),
    ]
