# Generated by Django 4.2.27 on 2026-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('registration_code', models.CharField(max_length=100)),
                ('trade_name', models.CharField(max_length=100)),
                ('nzbn', models.CharField(max_length=100)),
            ],
        ),
    ]
