# Generated by Django 4.2.27 on 2026-01-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Client',
        ),
    ]
