# Generated by Django 4.2.27 on 2026-01-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_manager_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='occupation',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Handyman', 'Handyman')], max_length=100),
        ),
    ]
