# Generated by Django 4.2.27 on 2026-01-19 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('about_myself', models.TextField(blank=True, null=True)),
                ('promo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_content1', models.TextField(blank=True, null=True)),
                ('promo_content2', models.TextField(blank=True, null=True)),
                ('promo_content3', models.TextField(blank=True, null=True)),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='manager.client')),
            ],
        ),
    ]
