# Generated by Django 4.2.27 on 2026-01-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_trader_photo_trader_promo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='promo_image',
            field=models.ImageField(blank=True, default='default_promo.png', null=True, upload_to='media/'),
        ),
    ]
